# Generated by Django 3.1.2 on 2020-10-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='active',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
