# Generated by Django 3.1.2 on 2020-10-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201025_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
