version: '3'

services:
  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./todo-backend:/app/backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    command: ["npm", "run", "dev"]
    volumes:
      - ./todo-frontend:/app/frontend
      - ./todo-frontend/node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: